version: '2'

services:
  ruby:
    build:
      context: ../..
      dockerfile: docker/release/Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${HTTP_PORT}"
